// frontend/src/views/LoginView.tsx
import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@/hooks/useAuth';
import { Button } from '@/components/Button/Button';

import choclotin from '@/assets/chcolotin.png';

export const LoginView: React.FC = () => {
  const navigate = useNavigate();
  const { login, loading, isAuthenticated } = useAuth();
  const [credentials, setCredentials] = useState({
    email: '',
    password: ''
  });
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (isAuthenticated && !loading) {
      navigate('/dashboard');
    }
  }, [isAuthenticated, loading, navigate]);

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-yellow-50 to-green-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin text-4xl mb-4">🌽</div>
          <p className="text-green-600">Verificando sesion...</p>
        </div>
      </div>
    );
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    try {
      await login(credentials);
      navigate('/dashboard');
    } catch {
      setError('Email o contraseña incorrectos');
    }
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setCredentials(prev => ({
      ...prev,
      [name]: value
    }));
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-yellow-50 to-green-50 flex items-center justify-center px-4">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="max-w-md w-full space-y-8"
      >
        {/* Logo and Title */}
        <div className="text-center">
          <motion.div
            initial={{ scale: 0 }}
            animate={{ scale: 1 }}
            transition={{ delay: 0.2 }}
            className="mx-auto h-24 w-24 mb-4"
          >
            <img
              src={choclotin}
              alt="Choclotin"
              className="h-24 w-24 rounded-full object-cover"
            />
          </motion.div>
          <h2 className="text-3xl font-bold text-green-800">
            Bienvenido a Bob's Corn
          </h2>
          <p className="mt-2 text-sm text-gray-600">
            Inicia sesión en tu cuenta
          </p>
        </div>

        {/* Login Form */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.3 }}
          className="bg-white rounded-2xl shadow-lg p-8"
        >
          <form className="space-y-6" onSubmit={handleSubmit}>
            {error && (
              <motion.div
                initial={{ opacity: 0, y: -10 }}
                animate={{ opacity: 1, y: 0 }}
                className="bg-red-50 border border-red-300 text-red-700 px-4 py-3 rounded-lg text-sm"
              >
                {error}
              </motion.div>
            )}

            <div>
              <label htmlFor="email" className="block text-sm font-medium text-gray-700">
                Email
              </label>
              <input
                id="email"
                name="email"
                type="email"
                autoComplete="email"
                required
                className="mt-1 appearance-none relative block w-full px-3 py-3 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                placeholder="admin@bobscorn.com"
                value={credentials.email}
                onChange={handleInputChange}
              />
            </div>

            <div>
              <label htmlFor="password" className="block text-sm font-medium text-gray-700">
                Contraseña
              </label>
              <input
                id="password"
                name="password"
                type="password"
                autoComplete="current-password"
                required
                className="mt-1 appearance-none relative block w-full px-3 py-3 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                placeholder="Ingresa tu contraseña"
                value={credentials.password}
                onChange={handleInputChange}
              />
            </div>

            <div>
              <Button
                type="submit"
                disabled={loading}
                className="w-full flex justify-center py-3 px-4 border border-transparent rounded-lg shadow-sm text-sm font-medium text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {loading ? (
                  <div className="flex items-center">
                    <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                    Iniciando sesión...
                  </div>
                ) : (
                  'Iniciar Sesión'
                )}
              </Button>
            </div>

            <div className="text-center">
              <p className="text-xs text-gray-500">
                Credenciales de prueba: admin@bobscorn.com / admin123
              </p>
            </div>
          </form>
        </motion.div>
      </motion.div>
    </div>
  );
};

// frontend/src/views/LoginView.vue
<script setup lang="ts">
import { ref } from 'vue';
import Card from 'primevue/card';
import choco from "@/assets/chcolotin.png"
import { APP_CONFIG } from '@/config/app';
import ViewContainer from '@/components/Commons/ViewContainer.vue';
import Button from "primevue/button"
import { useRouter } from 'vue-router';
import InputText from 'primevue/inputtext';
import Password from 'primevue/password';
import { useAuth } from '@/composables/useAuth';
import { APP_ROUTES } from '@/router/routes';

const router = useRouter();

const email = ref('');
const password = ref('');

const goBack = () => {
  console.log(router);

  router.push(APP_ROUTES.HOME);
};

const { login } = useAuth();

const onSubmit = async () => {
  try {
    await login({ email: email.value, password: password.value });
    router.push("/dashboard");
  } catch (error) {
    console.error("Login failed:", error);
  }
};

//TODO : Agregar manejo de errores y validaciones
</script>

<template>

  <Button icon="pi pi-arrow-left" class="m-4" rounded aria-label="Go back" @click="goBack" />

  <ViewContainer>
    <img :src="choco" alt="Chocolotin" class="h-24 w-24 object-contain" v-motion :initial="{ scale: 0 }"
      :enter="{ scale: 1 }" :duration="300" />
    <div class="flex flex-col items-center gap-2" v-motion :initial="{ opacity: 0, y: 50 }"
      :enter="{ opacity: 1, y: 0 }" :duration="300">
      <span class="text-2xl md:text-4xl font-bold text-green-800 border-b-2 border-yellow-400 pt-1">
        Bienvenido a {{ APP_CONFIG.app.name }}
      </span>
      <span class="text-green-800">
        Inicia sesión en tu cuenta
      </span>
    </div>
    <Card class="max-w-lg w-full" v-motion :initial="{ opacity: 0, y: 50 }" :enter="{ opacity: 1, y: 0 }"
      :duration="300" :delay="200">
      <template #content>
        <form @submit.prevent="onSubmit" class="flex flex-col gap-4">
          <div class="flex flex-col gap-2">
            <label for="email" class="font-bold text-sm text-gray-700">Usuario</label>
            <InputText id="email" v-model="email" placeholder="Ingresa tu email" class="w-full" required />
          </div>

          <div class="flex flex-col gap-2">
            <label for="password" class="font-bold text-sm text-gray-700">Contraseña</label>
            <Password id="password" v-model="password" placeholder="Ingresa tu contraseña" class="w-full"
              :feedback="false" toggleMask fluid required />
          </div>
          <Button type="submit" label="Iniciar Sesión" class="w-full mt-4" severity="success"
            :disabled="!email || !password" />

        </form>
      </template>
    </Card>
  </ViewContainer>
</template>
